<?php

namespace Poznet\ImageOptimBundle\Entity;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{

    public function sumOfAllImages(){
        return $this->getEntityManager()->createQuery("
            SELECT SUM(I.sizebefore) FROM PoznetImageOptimBundle:Image I
            "
        )->getSingleScalarResult();
    }
}
